### ISSUE TITLE
voom latex for .dtx file

### ISSUE THREAD

**Issue by maieul** [vim-voom/vim-voom.github.com#21]
Hi,

in LaTeX, the .dtx file are exception. The % at the begining of a line doesn't mean a commentary.

So

```
%\section{Section}
%\section{Other section}
```

Should be  marked in the plan, if we are in a .dtx file.

Should it be possible to add such option?

**Comment by vim-voom** [comment]
My initial thought is that this will have to be a separate markup mode
based on latex.
Probably just need to change regexps so that they require % at start of line.

If % is not a comment, what is? Do .dtx file have comments?

It would help if you pointed me to real and big .dtx files as examples.

**Comment by maieul** [comment]
In a .dtx file, A `%` is not a comment. A `%%` is a comment.

For example: http://ctan.mirrors.hoobly.com/macros/latex/contrib/eledmac/eledmac.dtx.

About the .dtx file and the way commentar are marked: http://mirror.math.ku.edu/tex-archive/info/dtxtut/dtxtut.pdf

**Comment by vim-voom** [comment]
Here is new markup mode for .dtx files:
https://raw.githubusercontent.com/vim-voom/VOoM_extras/master/markup_modes/voom_mode_dtx.py

Place it in $HOME/(vimfiles|.vim)/autoload/voom, invoke with
	:Voom dtx

This dtx module is almost identical to latex module. It's obviously a
terrible coding practice on my part to have two different modules with
almost identical code. The duplicate code needs to be reworked into a
class or library.

It works exactly like the LaTeX mode except that only commented lines
are considered.
Commented lines start with: optional leading whitespace, at least one
% character, optionally followed by any combination of % and
whitespace.
The following are all valid sectioning commands:

	%\section{Introduction}
	 % \section{Introduction}
	%% \section{Introduction}
	%%% % % \section{Introduction}

The string of leading % and whitespace is preserved during outline operations.

Headlines are ignored inside blocks:

	\begin{verbatim}
	...
	\end{verbatim}

	\begin{comment}
	...
	\end{comment}

	\begin{macrocode}
	...
	\end{macrocode}

It would be good to also ignore \iffalse...\fi blocks. But this is
harder to implement. I think false headlines are very unlikely in real
files.

I decided to ignore the difference between % and %% comments because I
do not understand how they work. There is this line in eledmac.dtx:

% % \section{Familiar footnotes}

The corresponding section is present in the eledmac.pdf. This made me
conclude that headlines can have any combination of leading % and
whitespace. Let me know if there are any problems.

**Comment by maieul** [comment]
That seems to work nice.

Thank you very much !

Indeed the way comments work in .dtx file is not clear also for me�

The \iffalse section doesnt not matter. It is very short.

**Comment by maieul** [comment]
it seems the << >> tools to change level don't work.

**Comment by vim-voom** [comment]
On 6/19/15, Maïeul Rouquette <notifications@github.com> wrote:
> it seems the << >> tools to change level don't work.

Impossible. Works for me. For example, with your eledmac.dtx, with
cursor on line 9 in the Tree pane
  |The \Eledmac{} package
>> moves right, << moves left.

I also made a test .dtx file as always and ran it through the test
suite without problems. It's identical to the latex mode.

Perhaps another plugin interfers with << >> mappings? Try other
mappings for moving left/right:
	Ctrl-Left, Ctrl-Right
	<LocalLeader>l, <LocalLeader>r

**Comment by maieul** [comment]
strange, it seems >> works but not << on a \subsection. But it is in all case, not only .dtx. I have disabled all my plugin except voom + pathogen and same problem...

**Comment by vim-voom** [comment]
On 6/20/15, Maïeul Rouquette <notifications@github.com> wrote:
> strange, it seems >> works but not << on a \subsection. But it is in all
> case, not only .dtx. I have disabled all my plugin except voom + pathogen
> and same problem...


By default, Move Left is allowed only if nodes are at the end of their subtree.
Please see VOoM help for g:voom_always_allow_move_left for details.

To always allow Move Left, add to .vimrc and restart Vim:
	let g:voom_always_allow_move_left = 1

I should make the above default. This restriction exists for some
historical reasons and because it is my personal preference.

**Comment by maieul** [comment]
ok. thanks and sorry for not reading the manual. that was so contre-intuitive for me ;-)

**Comment by vim-voom** [comment]
Included in VOoM v5.2. It is called latexDtx.
