### ISSUE TITLE
[Feature Request] Option to change the characters VOom uses for marks and indention

### ISSUE THREAD

**Issue by Cutuchiqueno** [vim-voom/vim-voom.github.com#27]
It would help me a lot if I could change the characters that VOom uses for things like foldlevel, current fold etc. (`.`, `|`, `=`). I also tried to do it directly in the code but didn't succeed.

(Let me please also express my deep gratitude for providing this plugin. I write my PhD in Pandoc Markdown and without this PlugIn it would have been hardly doable!)

**Comment by vim-voom** [comment]
What is wrong with `.`, `|`, `=` ? What do you want to change them to?
I settled on these characters in 2009. Not easy to change them now.
They are hard-coded as literal strings in a multitude of places both
in Vim script and Python code.

**Comment by Cutuchiqueno** [comment]
thanks for responding in the first place.

There is nothing 'wrong' about these characters specifically. The general background for my request is that of distraction. Thus my basic goal would be to replace all of them with whitespaces except the equation mark to have a distraction free UI. For me personally the indention is enough 'syntax'. But of cause it makes no sense to change the something if the effort is too much.

**Comment by vim-voom** [comment]
Ideally, this should be an option like everything else that deals with
appearances. It also would be nice to have an option to use fancy
Unicode drawing chars instead of "." and "|". Adding such options is
not easy and I am not interested. Therefore, I am not going to do it.

I never get distracted by "=", ".", "|" probably because I view them
not as ordinary chars but as ASCII art which simulates a GUI tree
widget. They create distinct look for Tree buffers which makes them
instantly recognizable.

"=" was chosen because when the cursor is on such line, current line
number equals selected node number.

"." form vertical and horizontal guides which indicate levels and make
it easy to do mouse clicks.

"|" create uniform look and vertical guides for headline text. They
make it obvious when headline text is an empty string and permit
leading whitespace in headline text. They make some parts of Vim
script code simple and efficient (e.g., folding function is as fast as
possible).

**Comment by Cutuchiqueno** [comment]
It is very kind of you to explain all your decisions in detail and I can completely follow your line of arguments.

I also understand that you are not interested. Nevertheless, thank you for commenting on it
