### ISSUE TITLE
Include comments in Markdown outline?

### ISSUE THREAD

**Issue by naught101** [vim-voom/vim-voom.github.com#28]
I use HTML paragraph-header summary comments in my Pandoc markdown so that it is easy to scroll through a large document and get a quick overview of the flow of ideas.

It would be really useful if these comments could be (optionally) included in the Voom outline. They would ideally sit two levels deeper than their parent header (to distinguish them a bit more from the next level subheadings). Is there already a way to achieve something like this? If not, could there be?

Personally I'd be happy with just including all HTML comments, because I don't use them for anything else anyway. But it might also be nice to just be able to include specific comments (e.g. comments that are only at the start of a line, or comments that start with `<!--# ...` or something).

**Comment by vim-voom** [comment]
No. I will not do this. Comments cannot be headlines. Too convoluted
and difficult to implement.

**Comment by naught101** [comment]
Fair enough, I guess. 

Just to be clear, is it the case that if headers are used for outlining (as with pandoc), then other fold markers can not be used simultaneously?

And if that is not possible, do you think it would be possible create a modified version of the FoldText function at https://github.com/vim-pandoc/vim-pandoc/blob/master/autoload/pandoc/folding.vim#L286 that could catch specific fold markers as well as headers?

**Comment by vim-voom** [comment]
On 4/5/18, naught101 <notifications@github.com> wrote:
> Fair enough, I guess.
>
> Just to be clear, is it the case that if headers are used for outlining (as
> with pandoc), then other fold markers can not be used simultaneously?

Headers need to be similar to each other in syntax and behavior,
otherwise it becomes a mess. The difficult part is implementing
outline operations. Unlike standard Markdown headers, your comment
headers don't have a level associated with them and need to be handled
in some special way during outline operations when level is changed.


> And if that is not possible, do you think it would be possible create a
> modified version of the FoldText function at
> https://github.com/vim-pandoc/vim-pandoc/blob/master/autoload/pandoc/folding.vim#L286
> that could catch specific fold markers as well as headers?

I do not know. This is not my code.

**Comment by vim-voom** [comment]
Closing this. Will not do.

**Comment by vim-voom** [comment]
VOoM markdown and pandoc modes do not know anything about HTML comments.
You can thus put headers in HTML comments like this:

    # Topic

    ## Subtopic
    

    ## Another subtopic

The `c` in front of the header is to indicate that this header is part
of a comment and should not be moved by itself. Or you can write `####`
instead of `###c` to get it sitting two levels deeper.

The blank line after `<!--` is required in pandoc mode, but not in markdown mode.

Any chance this is you want?

**Comment by naught101** [comment]
It takes up a lot of space, but it's definitely a good work-around. Thanks!
