### ISSUE TITLE
How to save/restore tree folding expanded/contracted status for "Voom markdown"

### ISSUE THREAD

**Issue by hw712** [vim-voom/vim-voom.github.com#29]
I'm using Voom for markdown documents, which is very brilliant. The only problem is everytime when I reopen the document, the tree folding status will lost and restored to default. 

I tried vim view and sessions to save the expanded/contracted status, they don't work. I read the help documents below, it seems that markdown is not supported.

> Save or Restore Tree Folding   [[[4~
>                                                  *voom-tree-folding*
> NOTE: These commands are only available when working with numbered start fold
> markers, that is in "fmr" modes (|voom-mode-fmr|, |voom-mode-fmr1|).
> 
> Opened/closed folds in a Tree buffer are equivalent to expanded/contracted
> nodes. VOoM allows to save and restore Tree buffer folding. To do this, it
> relies on special marks in Body headlines: character "o" immediately after the
> start fold marker level number or after optional "x" (|voom-special-marks|).
> The "o" mark indicates that the fold is opened. Such folds are opened
> automatically on startup. (This help file uses "o" marks.)

Can you or anyone else give me some advice? I'm a Java/Python developer but I'm not very familiar with VIMScript, can you suggest which function in voom.vim that I can dive into? Thanks!

I'm thinking that maybe by adding an extra special mark for my markdown headers to solve this problem. For example:
```
Head2 [[[c]]]
------------------------------
```
means the "Head2" will always be closed(contracted) when re-open the document. It seems that I need to run "normal! zc" in this line, but I haven't find out a correct solution in the voom.vim or the related Python code.

Best Regards
Henry

**Comment by vim-voom** [comment]
No, this is not possible for Markdown outlines.

Tree buffer folding can only be saved when using an fmr mode, that is
when working with fold markers {{{1, {{{2, etc. This is done by
placing "o" marks in the source file so that "{{{1" becomes "{{{1o" to
indicate that this Tree headline should be opened. (This is my own
invention, not Vim specification.) With other markups such as Markdown
this is not possible because there is no obvious place in headlines
where such marks can be placed.

VOoM does support Session files created with :mksesssion, albeit not
perfectly. However, my experiments with :mksession show that folding
of Tree buffers is never saved. VOoM Tree buffers are specially
configured, no-file buffers. The problem seems to be setting
"buftype=nofile". :mksession does not save buffer folding after "set
buftype=nofile". Since this setting is essential, there is nothing I
can do about it. :mkview seems to have the same problem. (I don't
really know how use :mkview with VOoM.)

Thus :mksession and :mkview are of no help.

It is possible to change initial 'foldlevel' for Tree buffers. Default
for Markdown and other non-fmr modes is 2. To do this for all markups,
create file
	~/.vim/after/ftplugin/voomtree.vim
with line
	setl fdl=1
This can also be done in a markup-specific fashion. There is example
in help file.

**Comment by hw712** [comment]
Hi @vim-voom ,

Thank you for your kind response. 

> when working with fold markers {{{1, {{{2, etc. This is done by placing "o" marks in the source file so that "{{{1" becomes "{{{1o" to indicate that this Tree headline should be opened. (This is my own invention, not Vim specification.) 

I want to extend a special version just for me, to support this feature for markdown, for example:
```
### Head1 [[[o]]] 
### Head2 [[[c]]] 
```
The [[[o]]] indicate that this Tree headline should be opened. Is it possible? If yes, which function in voom.vim should I dive into? I will spend my spare time to learn more about vim-script to implement it. If not possible then I will just let it go.

Right now, I'm working on function voom#TreeFoldexpr(lnum) as below:
```
func! voom#TreeFoldexpr(lnum) "{{{2

    " I added this part, just to test this issue.
    if (getline(a:lnum) == '  |head [[[c]]]')
        exe a:lnum   " go to this line. But this command return error.
        exe 'normal! zc'  " close this node.
    endif

    let ind = stridx(getline(a:lnum),'|') / 2
    let indn = stridx(getline(a:lnum+1),'|') / 2
    return indn>ind ? '>'.ind : ind-1
    "return indn>ind ? '>'.ind : indn<ind ? '<'.indn : ind-1
    "return indn==ind ? ind-1 : indn>ind ? '>'.ind : '<'.indn
endfunc

```

Thanks & Best Regards,
Henry

**Comment by vim-voom** [comment]
> I want to extend a special version just for me, to support this feature for markdown, for example:
> 
> ### Head1 [[[o]]] 
> ### Head2 [[[c]]] 
> 
> The [[[o]]] indicate that this Tree headline should be opened. Is it possible? If yes, which function in voom.vim should I dive into? I will spend my spare time to learn more about vim-script to implement it. If not possible then I will just let it go.

It's better to use html comments in case you need to convert to .html
(works for me with Pandoc converter):

    # headline 
    ## child headline

    another headline 
    ================
    ## child headline

Tree folding is created from "o" marks (fmr modes only) during :Voom
command by Python code:
file `autoload/voom/voom_vimplugin2657/voom_vim.py`,
function `voom_TreeCreate()`.

Change this block in `voom_TreeCreate()`

    # VO.MTYPE other than 0 means it is not an "fmr" mode
    if VO.MTYPE:
        computeSnLn(body, blnr)
        # reST, wiki files often have most headlines at level >1
        vim.command('setl fdl=2')
        return

to this

    # VO.MTYPE other than 0 means it is not an "fmr" mode
    if VO.MTYPE:
        computeSnLn(body, blnr)
        if VO.mmode == 'markdown' or VO.mmode == 'pandoc':
            # open folds marked with 
            bnodes = VO.bnodes
            Body = VO.Body
            z = len(bnodes)
            oFolds = []
            for i in xrange(1,z):
                bline = Body[bnodes[i]-1]
                if '' in bline:
                    oFolds.append(i+1)
            if oFolds:
                cFolds = foldingFlip(VO,2,z,oFolds)
                foldingCreate(2,z,cFolds)
        else:
            # reST, wiki files often have most headlines at level >1
            vim.command('setl fdl=2')
        return

Now when you do `:Voom markdown` or `:Voom pandoc` Tree headlines with
`<!--o-->` in them will be opened, all other closed.

Commands :VoomFolding* will not work, you will have to add and remove
`<!--o-->` strings manually.

Since we are adding support for "o" marks, it makes sense to also add
support for "x" and "=" marks and the corresponding commands. This way
markdown and pandoc modes will gain all features of fmr mode. Not sure
if it's worth the effort. These marks will be useless to the majority of
Markdown users since most users don't use Vim and VOoM.

**Comment by hw712** [comment]
Hi @vim-voom ,

Thank you so much for your effort! It works for me too, and it really solved a big problem for me. Because I use Vim and VOoM for all my personal notes and daily diary for years. Now it works almost perfect. 

I will use this feature in my local VOoM code environment. And I hope that I can optimize this feature to fit my requirements in the future, such as remove the `<!--o-->` part from "Tree" because there's no need to show the mark in the Tree.

* UPDTAE: I have solved this requirement: remove `<!--o-->` mark from `Tree`, by update  `autoload/voom/voom_vimplugin2657/voom_vim.py`
```
def updateTree(body,tree): #{{{2
    ......

    ### Add the = mark.
    snLn = VO.snLn
    Z = len(bnodes)
    # snLn got larger than the number of nodes because some nodes were
    # deleted while editing the Body
    if snLn > Z:
        snLn = Z
        vim.command('call voom#SetSnLn(%s,%s)' %(body,snLn))
        VO.snLn = snLn
    tlines[snLn-1] = '=%s' %tlines[snLn-1][1:]

    ### Add this part to remove <!--o--> mark from "Tree"
    for i in range(0, len(tlines)):
        if "<!--o-->" in tlines[i]:
            tlines[i] = tlines[i].replace("<!--o-->", "")

    ......
```
This maybe useless for others but it's important for me. Thanks again for bring us such a brilliant plug-in!

Regards,
Henry
